/*
Claude Program.c
Gives user 3 changes to guess a number 1-10
All code was generated by Gemini, Claude, or myself
Erick Marte
9/8/2026
9/9/2026
*/ 

#include <stdio.h>

int main(void) {
    int secret = 7;
    int guess;
    int attempts = 3;
    int won = 0;

    printf("Guess a number between 1 and 10.\n");

    for (int i = 1; i <= attempts; i++) {
        printf("Attempt %d/%d. Enter your guess: ", i, attempts);
        scanf("%d", &guess);

        if (guess < secret) {
            printf("Too low! Try again.\n");
        } else if (guess > secret) {
            printf("Too high! Try again.\n");
        } else {
            printf("Correct! You win!\n");
            won = 1;
            break;
        }
    }

    if (!won) {
        printf("Out of attempts! The number was %d. You lose.\n", secret);
    }

    return 0;
}
